<h1>Cadastro de Funcionarios</h1>
<form method="post" action="<?= $this->url('application', ['action' => 'cadastrar']);?>">
    <div class="form-group">
        <label for="nome">Nome:</label>
        <input type="text" id="nome" name="nome" class="form-control">
    </div>
    <div class="form-group">
        <label for="email">Email:</label>
        <input type="email" id="email" name="email" class="form-control">
    </div>
    <div class="form-group">
        <label for="cpf">Cpf:</label>
        <input type="number" id="cpf" name="cpf" class="form-control">
    </div>
    <div class="form-group">
        <input type="submit" value="cadastrar" class="btn btn-primary">
    </div>
</form>