
<h1>Editar Funcionarios</h1>
<form method="post" action="<?= $this->url('application', ['action' => 'editar']);?>">

    <input type="hidden" value="<?=$pessoa->getId();?>" name="id">
    <div class="form-group">
        <label for="nome">Nome:</label>
        <input type="text" id="nome" name="nome" value="<?= $pessoa->getNome(); ?>" class="form-control">
    </div>
    <div class="form-group">
        <label for="email">Email:</label>
        <input type="email" id="email" name="email" value="<?= $pessoa->getEmail(); ?>" class="form-control">
    </div>
    <div class="form-group">
        <label for="cpf">Cpf:</label>
        <input type="number" id="cpf" name="cpf" value="<?= $pessoa->getCpf(); ?>" class="form-control">
    </div>
    <div class="form-group">
        <input type="submit" value="Salvar alterações" class="btn btn-primary">
    </div>
</form>