<h1>Listagem de Funcionarios</h1>

<table class="table table-striped">
    <thead>
        <th>Nome</th>
        <th>Email</th>
        <th>Cpf</th>
        <th>Acões</th>
    </thead>
    <tbody>
        <?php 

                foreach ($pessoa as $fun){
            ?>
            
                <tr>
                    <td><?= $fun->getNome();?></td>
                    <td><?= $fun->getEmail();?></td>
                    <td><?= $fun->getCpf();?></td>
                    <td><a href="<?= $this->url('application',['action' => 'editar','id' =>$fun->getId()])?>"  class="btn btn-info">Editar</a>
                    <a href="<?= $this->url('application',['action' => 'remover','id' =>$fun->getId()])?>"  class="btn btn-danger">Remover</a></td>
                </tr>
            <?php
            }
        
          ?>
    </tbody>
</table>